### PR TITLE
config json -> yml

### PR DESCRIPTION
**Pull request by subhojit777**
Issue #11

### CODE REVIEW

**Comment by AshishThakur** [comment]
@subhojit777: could you fix the conflict, else it looks good to me. Thanks for the effort 👍

**Comment by subhojit777** [comment]
I have to verify whether json -> yml transition is really working. I will try that on some buggy code. BTW, we need tests. Thanks @crazyrohila :)

**Comment by AshishThakur** [comment]
@subhojit777: can you fix the conflicts. I will pull the changes locally and check.

**Comment by subhojit777** [comment]
@AshishThakur Conflicts resolved, and the transition is tested locally. You can go ahead and merge this.

**Pull request merged**
